// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectBackEnd.DAL;

namespace ProjectBackEnd.Migrations
{
    [DbContext(typeof(NestDb))]
    [Migration("20220322165257_createdsection1searchestable")]
    partial class createdsection1searchestable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectBackEnd.Models.section1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("section1");
                });

            modelBuilder.Entity("ProjectBackEnd.Models.section1search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("section1Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("section1Id");

                    b.ToTable("section1search");
                });

            modelBuilder.Entity("ProjectBackEnd.Models.section1search", b =>
                {
                    b.HasOne("ProjectBackEnd.Models.section1", null)
                        .WithMany("section1Searches")
                        .HasForeignKey("section1Id");
                });
#pragma warning restore 612, 618
        }
    }
}
